server:
  compression:
    enabled: true
    # 配置哪些 MIME 类型的内容会被压缩，默认包括了大部分文本类型
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    # 只有当响应体的大小大于或等于这个值（以字节为单位）时才会启用压缩，默认是 2048 字节
    min-response-size: 1024
  port: 8080
spring:
  application:
    name: video-stream-middleware
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}